language: rust
rust: nightly
sudo: false

env:
  global:
    - RUST_BACKTRACE=1
    - secure: E33II/ctVUNigc5wuh153OX/7RUje43G3I9i5+PibEiFPCpKIJpHZA9LfKHABqOBVPgBLdWkretWgKn4Whfb9e2NMC8Nzn8Pch68b7yPZ2Ee0zLWr2M2gJ95PwTn3ZyFaMuZOAa+TgEU9buVIXTdgM+FHK+jXwU0qqNL2XCF5YM=
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev
      - g++

install:
  - rustup component add rustfmt-preview
  - mkdir -p ~/.cargo/bin
  - sh install_kcov.sh
  - export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$PATH
  - export RUSTFLAGS="-C link-dead-code"
  - kcov --version
  - cargo install cargo-kcov

script:
  - cargo fmt --all -- --check
  - cargo build
  - cargo test --all

after_success:
  - cargo kcov --verbose --no-clean-rebuild --all --coveralls

before_deploy:
  - cargo clean
  - cargo run --release --bin coverage -- --json coverage.json

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
