language: rust
rust: nightly
sudo: false

env:
  global:
    - RUST_BACKTRACE=1
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - RUSTFLAGS="-C link-dead-code"
    - LD_LIBRARY_PATH="$TRAVIS_BUILD_DIR/target/debug/deps"

# `sudo`-less apt install.
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
        # Needed for `travis-cargo coveralls --no-sudo`
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

cache:
  directories:
    - $HOME/.cargo

# Load `travis-cargo`
before_script:
    - pip install 'git+https://github.com/euclio/travis-cargo@kcov' --user
    - export PATH=$HOME/.local/bin:$PATH

script:
   - echo 'hi'

# Generate coverage
after_success:
    - cd $TRAVIS_BUILD_DIR
    - travis-cargo -q coveralls --no-sudo
